services:
  - type: web
    name: photobook
    runtime: node
    buildCommand: apt-get install -y chromium-browser && npm run install:all && npm run build
    startCommand: node backend/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: BACKEND_URL
        sync: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
